In [57]:
import pandas as pd
import numpy as np
import os

In [58]:
csv1 = "Belly_Button_Biodiversity_Metadata.csv"
csv2 = "belly_button_biodiversity_otu_id.csv"
csv3 = "belly_button_biodiversity_samples.csv"
csv4 = "metadata_columns.csv"

In [59]:
bbb_df = pd.read_csv(csv1, dtype=object)
otu_df = pd.read_csv(csv2, dtype=object)
bbbs_df = pd.read_csv(csv3, dtype=object)
columns_df = pd.read_csv(csv4, dtype=object)

In [60]:
bbb_df.head()

,SAMPLEID,EVENT,ETHNICITY,GENDER,AGE,WFREQ,BBTYPE,LOCATION,COUNTRY012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24,2,I,Beaufort/NC,usa,22306,...,no,no,8852,37.17222214,54.5,NaN,1,NaN,33.99000168,25.5
1,941,NaN,Caucasian/Midleastern,F,34,1,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49,1,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44,1,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.81666565,16,NaN,0,6567,32.40333176,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48,1,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.78333282,4,NaN,0,5613,33.63444519,24

In [61]:
bbb_df['SAMPLEID']

0       940
1       941
2       943
3       944
4       945
5       946
6       947
7       948
8       949
9       950
10      952
11      953
12      954
13      955
14      956
15      958
16      959
17      960
18      961
19      962
20      963
21      964
22      966
23      967
24      968
25      969
26      970
27      971
28      972
29      973
       ...
123    1540
124    1541
125    1542
126    1543
127    1544
128    1545
129    1546
130    1547
131    1548
132    1549
133    1550
134    1551
135    1552
136    1553
137    1554
138    1555
139    1556
140    1557
141    1558
142    1561
143    1562
144    1563
145    1564
146    1572
147    1573
148    1574
149    1576
150    1577
151    1581
152    1601
Name: SAMPLEID, Length: 153, dtype: object

In [62]:
bbb_df

,SAMPLEID,EVENT,ETHNICITY,GENDER,AGE,WFREQ,BBTYPE,LOCATION,COUNTRY012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24,2,I,Beaufort/NC,usa,22306,...,no,no,8852,37.17222214,54.5,NaN,1,NaN,33.99000168,25.5
1,941,NaN,Caucasian/Midleastern,F,34,1,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49,1,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44,1,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.81666565,16,NaN,0,6567,32.40333176,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48,1,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.78333282,4,NaN,0,5613,33.63444519,24
5,946,BellyButtonsScienceOnline,Caucasian,F,42,3,I,Deerfield/MA,usa,12538,...,no,yes,NaN,34.76111221,15.5,NaN,0,6273,29.40333366,67.5
6,947,BellyButtonsScienceOnline,Caucasian,M,49,6,I,ChapelHill/NC,usa,48823,...,no,yes,7491,30.35666656,31,NaN,0,5357,30.88111115,16.5
7,948,BellyButtonsScienceOnline,Caucasian,M,20,NaN,I,ChapelHill/NC,usa,27613,...,no,no,NaN,53.88777924,0,NaN,31,NaN,31.72999954,22.5
8,949,BellyButtonsScienceOnline,Caucasian,F,51,3,I,Durham/NC,usa,7009,...,no,no,NaN,35.5344429,36,NaN,5,NaN,35.5344429,36
9,950,BellyButtonsScienceOnline,Caucasian,M,51,5,I,NewYork/NY,usa,1730,...,yes,no,6273,29.40333366,67.5,NaN,0,NaN,30.48111153,33
10,952,BellyButtonsScienceOnline,Caucasian,F,51,7,I,Seattle/WA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,953,BellyButtonsScienceOnline,Caucasian,F,38,2,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,954,BellyButtonsScienceOnline,Caucasian,M,26,7,I,NewYork/NY,usa,45429,...,NaN,NaN,6919,34.00777817,34.5,NaN,21,6074,34.26333237,14.5
13,955,BellyButtonsScienceOnline,Caucasian,F,27,7,I,NewYork/NY,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,956,BellyButtonsScienceOnline,Caucasian,M,16,7,I,Jacksonville/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,958,BellyButtonsScienceOnline,Caucasian,M,43,5,I,Wilmington/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,959,BellyButtonsScienceOnline,Caucasian,M,40,5,I,Carrboro/NC,usa,93605,...,no,no,7431,30.58333397,61.5,NaN,1,4066,38.14555359,1.5
17,960,BellyButtonsScienceOnline,Caucasian,M,48,7,I,Lexington/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,961,BellyButtonsScienceOnline,Caucasian,F,35,4,i,"Edmonton,AB",canada,K7V3Z4,...,yes,no,6962,33.80555725,15,NaN,'NA',5104,29.57666588,22
19,962,BellyButtonsScienceOnline,Caucasian,F,56,1,i,"Washington,DC",usa,60514,...,no,no,7281,29.95444489,37.5,NaN,23,NaN,37.20777893,18
20,963,BellyButtonsScienceOnline,Caucasian,F,33,3.5,I,Ithaca/NY,usa,45238,...,no,no,5363,32.65000153,48.5,NaN,4,6420,33.33666611,18.5
21,964,BellyButtonsScienceOnline,Caucasian,F,43,7,I,UK/London,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,966,BellyButtonsScienceOnline,Caucasian,M,56,0,I,Needham/MA,usa,7924,...,no,no,4016,33.27444458,64,NaN,6,6762,31.6922226,65
23,967,BellyButtonsScienceOnline,Caucasian/Jewish,F,43,1,I,ChapelHill/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,968,BellyButtonsScienceOnline,Caucasian,F,38,6,I,St.Louis/MI,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,969,BellyButtonsScienceOnline,Caucasian/Asian,F,31,7,I,ChevyChase/MD,usa,7071,...,no,no,NaN,30.48111153,33,NaN,0,NaN,35.7788887,27
26,970,BellyButtonsScienceOnline,Caucasian,F,42,0,i,SanDiego/CA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,971,BellyButtonsScienceOnline,Asian(South),M,36,1,I,SantaBarbara/CA,usa,10533,...,no,no,NaN,37.20777893,18,NaN,70,5961,30.55666733,23.5
28,972,BellyButtonsScienceOnline,Caucasian,F,31,7,I,Charlotte/NC,usa,55987,...,yes,no,NaN,NaN,9,NaN,0,4949,29.61222267,57
29,973,BellyButtonsScienceOnline,Caucasian,F,4,1,I,Charlotte/NC,usa,28269,...,yes,no,9523,27.6455555,63,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,1540,BellyButtonsWildLives,Caucasian,M,30,0,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,1541,BellyButtonsWildLives,Caucasian,F,26,0,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,1542,BellyButtonsWildLives,Caucasian,M,36,NaN,I,NC,usa,37343and37221,...,no,no,NaN,34.98555756,27,NaN,'NA',4826,29.43888855,6.5
126,1543,BellyButtonsWildLives,Caucasian,F,34,3,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,1544,BellyButtonsWildLives,Caucasian,F,33,1,I,NC,usa,80106,...,yes,no,4464,33.80110931,1,NaN,0,2521,42.24777985,2
128,1545,BellyButtonsWildLives,Caucasian,F,39,7,I,NC,usa,92054,...,no,no,5647,29.86333275,34,NaN,0,5744,32.54111099,15
129,1546,BellyButtonsWildLives,Caucasian,M,34,3,I,NC,usa,13104,...,yes,no,NaN,35.7788887,27,NaN,0,7281,29.95444489,37.5
130,1547,BellyButtonsWildLives,NaN,M,38,0,I,NC,usa,92014,...,no,no,7817,29.69666672,17.5,NaN,36,NaN,36.61222076,10
131,1548,BellyButtonsWildLives,Caucasian,M,6,0,I,NC,usa,27607,...,yes,no,NaN,35.5344429,26,NaN,NaN,NaN,NaN,NaN
132,1549,BellyButtonsWildLives,Caucasian,F,37,3,I,NC,usa,28655,...,yes,no,6940,31.68111038,51.5,NaN,63,NaN,35.53222275,7.5
133,1550,BellyButtonsWildLives,Caucasian,F,29,7,I,NC,usa,55127,...,no,no,2521,42.24777985,2,NaN,0,NaN,33.1922226,NaN
134,1551,BellyButtonsWildLives,Caucasian,M,26,0,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,1552,BellyButtonsWildLives,Caucasian,M,25,3,I,NC,usa,63301,...,no,no,NaN,36.61222076,10,NaN,0,4464,33.80110931,1
136,1553,BellyButtonsWildLives,Caucasian,F,50,0,I,NC,usa,70808,...,yes,no,NaN,33.1922226,NaN,NaN,11,NaN,37.78333282,4
137,1554,BellyButtonsWildLives,Caucasian,F,18,0,I,NC,usa,27607,...,yes,no,6115,29.79444504,31.5,NaN,70,NaN,34.54111099,11
138,1555,BellyButtonsWildLives,Caucasian,M,26,0,I,NC,usa,8057,...,yes,yes,5104,29.57666588,22,NaN,42,NaN,36.4766655,32
139,1556,BellyButtonsWildLives,Hispanic,M,34,0,I,NC,colombia,NaN,...,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,1557,BellyButtonsWildLives,Caucasian,F,26,2,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,1558,BellyButtonsWildLives,Caucasian,M,26,1,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,1561,BellyButtonsWildLives,Caucasian,M,31,2,I,NC,usa,28515,...,no,yes,NaN,34.78333282,8.5,NaN,0,7817,29.69666672,17.5
143,1562,BellyButtonsWildLives,Caucasian,M,39,0,I,MT,usa,48640,...,yes,no,5081,43.45888901,4.5,NaN,0,6450,30.3722229,25
144,1563,BellyButtonsWildLives,Caucasian,F,31,0,I,MT,usa,36207,...,yes,no,NaN,24.20111084,9.5,NaN,0,7431,30.58333397,61.5
145,1564,BellyButtonsWildLives,Caucasian,F,36,5,I,NC,usa,27530,...,no,yes,5875,34.87889099,43.5,NaN,0,6843,34.34111023,10
146,1572,BellyButtonsWildLives,Caucasian,F,33,0,I,NC,Peru,Lima,...,no,no,NaN,37.22333145,14.5,NaN,'NA',NaN,NaN,NaN
147,1573,BellyButtonsWildLives,Caucasian,M,53,0,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,1574,BellyButtonsWildLives,Caucasian,M,30,7,I,OK,usa,66210,...,no,no,7131,29.14777756,40.5,NaN,3,NaN,39.67666626,9.5
149,1576,BellyButtonsWildLives,Caucasian,F,33,0,I,NC,usa,21045,...,no,yes,NaN,35.76111221,13.5,NaN,12,NaN,32.71888733,34.5
150,1577,BellyButtonsWildLives,Caucasian,M,26,0,I,NC,usa,21228,...,no,yes,893,40.22333145,0,NaN,23,NaN,36.27000046,27
151,1581,BellyButtonsWildLives,Asian(American),F,22,2,I,NC,usa,28056,...,no,no,5026,30.00111198,25.5,NaN,0,6962,33.80555725,15
152,1601,BellyButtonsWildLives,Caucasian,F,22,2,I,NC,usa,29615,...,yes,no,NaN,NaN,NaN,NaN,1,NaN,32.88999939,45.5

In [63]:
otu_df.head()

  otu_id                        lowest_taxonomic_unit_found
0      1  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
1      2  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
2      3  Archaea;Euryarchaeota;Halobacteria;Halobacteri...
3      4  Archaea;Euryarchaeota;Methanobacteria;Methanob...
4      5  Archaea;Euryarchaeota;Methanobacteria;Methanob...

In [64]:
bbbs_df.head()

,otu_id,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,BB_949,...,BB_1562,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [65]:
merged_df = pd.merge(otu_df, bbbs_df, on="otu_id", how="outer")
merged_df.head()

,otu_id,lowest_taxonomic_unit_found,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,...,BB_1562,BB_1563,BB_1564,BB_1572,BB_1573,BB_1574,BB_1576,BB_1577,BB_1581,BB_1601
0,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [66]:
merged_df2 = pd.concat([merged_df, bbb_df], axis=1)
merged_df2.head()

,otu_id,lowest_taxonomic_unit_found,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,no,no,8852,37.17222214,54.5,NaN,1,NaN,33.99000168,25.5
1,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,no,yes,NaN,35.81666565,16,NaN,0,6567,32.40333176,28.5
4,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,no,no,NaN,37.78333282,4,NaN,0,5613,33.63444519,24

In [67]:
merged_df2 = merged_df2.set_index("SAMPLEID")
merged_df2

,otu_id,lowest_taxonomic_unit_found,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
SAMPLEID,,,,,,,,,,,,,,,,,,,,,
940,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,no,no,8852,37.17222214,54.5,NaN,1,NaN,33.99000168,25.5
941,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
944,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,no,yes,NaN,35.81666565,16,NaN,0,6567,32.40333176,28.5
945,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,no,no,NaN,37.78333282,4,NaN,0,5613,33.63444519,24
946,6,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,no,yes,NaN,34.76111221,15.5,NaN,0,6273,29.40333366,67.5
947,7,Bacteria,0,0,0,0,0,0,0,0,...,no,yes,7491,30.35666656,31,NaN,0,5357,30.88111115,16.5
948,8,Bacteria,0,0,0,0,0,0,0,0,...,no,no,NaN,53.88777924,0,NaN,31,NaN,31.72999954,22.5
949,9,Bacteria,0,0,0,0,0,1,0,0,...,no,no,NaN,35.5344429,36,NaN,5,NaN,35.5344429,36
950,10,Bacteria,0,0,0,0,0,0,0,0,...,yes,no,6273,29.40333366,67.5,NaN,0,NaN,30.48111153,33
952,11,Bacteria,1,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
953,12,Bacteria,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
954,13,Bacteria,0,0,0,0,0,0,0,0,...,NaN,NaN,6919,34.00777817,34.5,NaN,21,6074,34.26333237,14.5
955,14,Bacteria,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
956,15,Bacteria,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
958,16,Bacteria,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
959,17,Bacteria,0,0,0,0,0,0,0,0,...,no,no,7431,30.58333397,61.5,NaN,1,4066,38.14555359,1.5
960,18,Bacteria,0,0,0,0,0,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961,19,Bacteria,1,0,0,0,0,0,0,0,...,yes,no,6962,33.80555725,15,NaN,'NA',5104,29.57666588,22
962,20,Bacteria,0,0,0,0,0,0,0,0,...,no,no,7281,29.95444489,37.5,NaN,23,NaN,37.20777893,18
963,21,Bacteria,0,0,0,0,0,0,0,0,...,no,no,5363,32.65000153,48.5,NaN,4,6420,33.33666611,18.5
964,22,Bacteria,1,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,23,Bacteria,0,0,0,0,0,0,0,0,...,no,no,4016,33.27444458,64,NaN,6,6762,31.6922226,65
967,24,Bacteria,1,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
968,25,Bacteria,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
969,26,Bacteria,0,0,0,0,0,0,0,0,...,no,no,NaN,30.48111153,33,NaN,0,NaN,35.7788887,27
970,27,Bacteria,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
971,28,Bacteria,0,0,0,0,0,0,0,0,...,no,no,NaN,37.20777893,18,NaN,70,5961,30.55666733,23.5
972,29,Bacteria,0,0,0,0,0,0,0,0,...,yes,no,NaN,NaN,9,NaN,0,4949,29.61222267,57
973,30,Bacteria,0,0,0,0,0,0,0,0,...,yes,no,9523,27.6455555,63,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,3645,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3646,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3647,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3648,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3649,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3650,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3651,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3652,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3653,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3654,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3655,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3656,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3657,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3658,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3659,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3660,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3661,Bacteria;Synergistetes;Synergistia;Synergistal...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3662,Bacteria;TM7;TM7_genera_incertae_sedis,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3663,Bacteria;Verrucomicrobia;Spartobacteria;Sparto...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3664,Bacteria;Verrucomicrobia;Spartobacteria;Sparto...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3665,Bacteria;Verrucomicrobia;Spartobacteria;Sparto...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3666,Bacteria;Verrucomicrobia;Verrucomicrobiae;Verr...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3667,Unclassified,0,0,0,0,0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3668,Unclassified,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3669,Unclassified,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3670,Unclassified,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3671,Unclassified,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3672,Unclassified,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3673,Unclassified,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3674,Unclassified,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
merged_df2.replace('0', np.NaN)

,otu_id,lowest_taxonomic_unit_found,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
SAMPLEID,,,,,,,,,,,,,,,,,,,,,
940,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,8852,37.17222214,54.5,NaN,1,NaN,33.99000168,25.5
941,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
944,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,yes,NaN,35.81666565,16,NaN,NaN,6567,32.40333176,28.5
945,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,NaN,37.78333282,4,NaN,NaN,5613,33.63444519,24
946,6,Archaea;Euryarchaeota;Methanobacteria;Methanob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,yes,NaN,34.76111221,15.5,NaN,NaN,6273,29.40333366,67.5
947,7,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,yes,7491,30.35666656,31,NaN,NaN,5357,30.88111115,16.5
948,8,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,NaN,53.88777924,NaN,NaN,31,NaN,31.72999954,22.5
949,9,Bacteria,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,no,no,NaN,35.5344429,36,NaN,5,NaN,35.5344429,36
950,10,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,yes,no,6273,29.40333366,67.5,NaN,NaN,NaN,30.48111153,33
952,11,Bacteria,1,NaN,NaN,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
953,12,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
954,13,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6919,34.00777817,34.5,NaN,21,6074,34.26333237,14.5
955,14,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
956,15,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
958,16,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
959,17,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,7431,30.58333397,61.5,NaN,1,4066,38.14555359,1.5
960,18,Bacteria,NaN,NaN,NaN,NaN,NaN,2,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961,19,Bacteria,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,yes,no,6962,33.80555725,15,NaN,'NA',5104,29.57666588,22
962,20,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,7281,29.95444489,37.5,NaN,23,NaN,37.20777893,18
963,21,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,5363,32.65000153,48.5,NaN,4,6420,33.33666611,18.5
964,22,Bacteria,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,23,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,4016,33.27444458,64,NaN,6,6762,31.6922226,65
967,24,Bacteria,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
968,25,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
969,26,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,NaN,30.48111153,33,NaN,NaN,NaN,35.7788887,27
970,27,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
971,28,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,no,no,NaN,37.20777893,18,NaN,70,5961,30.55666733,23.5
972,29,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,yes,no,NaN,NaN,9,NaN,NaN,4949,29.61222267,57
973,30,Bacteria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,yes,no,9523,27.6455555,63,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,3645,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3646,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3647,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3648,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3649,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3650,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3651,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3652,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3653,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3654,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3655,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3656,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3657,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3658,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3659,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3660,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3661,Bacteria;Synergistetes;Synergistia;Synergistal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3662,Bacteria;TM7;TM7_genera_incertae_sedis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3663,Bacteria;Verrucomicrobia;Spartobacteria;Sparto...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3664,Bacteria;Verrucomicrobia;Spartobacteria;Sparto...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3665,Bacteria;Verrucomicrobia;Spartobacteria;Sparto...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3666,Bacteria;Verrucomicrobia;Verrucomicrobiae;Verr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3667,Unclassified,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3668,Unclassified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3669,Unclassified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3670,Unclassified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3671,Unclassified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3672,Unclassified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3673,Unclassified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3674,Unclassified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
merged_df2.sort_values('SAMPLEID', ascending=True)
merged_df2.head()

,otu_id,lowest_taxonomic_unit_found,BB_940,BB_941,BB_943,BB_944,BB_945,BB_946,BB_947,BB_948,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,no,no,8852,37.17222214,54.5,NaN,1,NaN,33.99000168,25.5
1,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,no,yes,NaN,35.81666565,16,NaN,0,6567,32.40333176,28.5
4,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,no,no,NaN,37.78333282,4,NaN,0,5613,33.63444519,24

In [36]:
merged_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3674 entries, 0 to 3673
Columns: 177 entries, otu_id to PFC1319
dtypes: object(177)
memory usage: 5.0+ MB

In [10]:
columns_df.head()

      COLUMN     TYPE           DESCRIPTION
0   SAMPLEID  INTEGER             sample_id
1      EVENT     TEXT     Collection event
2  ETHNICITY     TEXT             Ethnicity
3     GENDER     TEXT  Gender (male/female)
4        AGE  INTEGER        Age (in years)